name: 'build-test'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install node dependencies
        run: |
          npm install
      - name: Build dist and run tests
        run: |
          npm run all

      - name: Run tests
        uses: ./
        with:
          path: __tests__
          dry-run: true
          check-repo: ${{ github.event_name == 'push' }}
